name: Hello world build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up permission for hello-world.sh script
      run: chmod +x hello-world.sh

    - name: Run hello-world.sh script
      run: ./hello-world.sh

    - name: Verify hello2.txt content
      run: |
        content=$(cat hello2.txt)
        if [ "$content" = "Hello, world!" ]; then
          echo "Test passed"
        else
          echo "Test failed"
          exit 1
        fi
