name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up permission for shell scripts
      run: chmod +x test.sh

    - name: Run test.sh script and capture output
      id: run_test_script
      run: |
        output=$(./test.sh 2>&1)
        echo "$output"
        echo "::set-output name=test_result::$(echo "$output" | tail -1)"

    - name: Display the result of the script
      run: echo "The result of test.sh is: ${{ steps.run_test_script.outputs.test_result }}"
