name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Extract commit message
      id: extract_message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Set up permission for shell scripts
      run: chmod +x test.sh

    - name: Run test.sh script
      run: ./test.sh


    - name: Send the test results to ServiceNow
      env:
        SNOW_INSTANCE: https://regionsdev.service-now.com
        SNOW_USERNAME: demo.user
        SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
        COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
      run: |
        incident_data=$(jq -n \
          --arg testKey "Hello from GitHub" \
          --arg commit_message "$COMMIT_MESSAGE" \
          '{testKey: $testKey, commit_msg: $commit_message}')
 
        echo "Generated incident data: $incident_data"
        
        curl -X POST \
          -H "Content-Type: application/json" \
          -u $SNOW_USERNAME:$SNOW_PASSWORD \
          --data "$incident_data" \
          $SNOW_INSTANCE/api/rfr/get_github_data

    - name: Display hello.txt content (for debugging)
      run: cat hello.txt
