name: CI

on: [push, pull_request]

jobs:
  
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up permission for shell scripts
      run: chmod +x test.sh

    - name: Run test.sh script
      run: ./test.sh
