name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up permission for shell scripts
      run: chmod +x hello-world.sh test.sh

    - name: Run hello-world.sh script
      run: ./hello-world.sh
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add hello.txt
        git commit -m 'Add hello.txt with "hello world"'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up permission for shell scripts
      run: chmod +x hello-world.sh test.sh

    - name: Run test.sh script
      run: ./test.sh
